[package]
name = "vicis_codegen_cranelift"
version = "0.1.0"
edition = "2018"

[dependencies]
vicis_core = { path = "../vicis_core" }
cranelift-jit = "= 0.76.0"
cranelift = "= 0.76.0"
cranelift-module = "= 0.76.0"
cranelift-codegen = "= 0.76.0"
