[package]
name = "runner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vicis_core = { path = "../vicis_core" }
vicis_codegen = { path = "../vicis_codegen" }
structopt = "0.3.18"
rand = "0.8.3"
